# Julia Basics

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Functions" data-toc-modified-id="Functions-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Functions</a></span></li><li><span><a href="#Strings" data-toc-modified-id="Strings-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Strings</a></span></li><li><span><a href="#Arrays" data-toc-modified-id="Arrays-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Arrays</a></span><ul class="toc-item"><li><span><a href="#Multidimensional-Arrays" data-toc-modified-id="Multidimensional-Arrays-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Multidimensional Arrays</a></span></li></ul></li><li><span><a href="#Dictionaries" data-toc-modified-id="Dictionaries-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Dictionaries</a></span></li><li><span><a href="#Loops-and-Maps" data-toc-modified-id="Loops-and-Maps-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Loops and Maps</a></span></li><li><span><a href="#Types" data-toc-modified-id="Types-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Types</a></span></li><li><span><a href="#I/O" data-toc-modified-id="I/O-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>I/O</a></span></li><li><span><a href="#DataFrames" data-toc-modified-id="DataFrames-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>DataFrames</a></span></li></ul></div>

In [1]:
print("Hello World")

Hello World

## Functions

In [2]:
function sphere_vol(r::Number)
    return 4/3*pi*r^3
end

print(sphere_vol(3))

113.09733552923254

In [3]:
sphere_vol_short(r) = (4/3*pi*r^3)
print(sphere_vol_short(3))

113.09733552923254

In [4]:
quadratic(a, sqr_term, b) = (-b + sqr_term)/2a

function quadratic2(a::Float64, b::Float64, c::Float64)
    
    sqr_term = sqrt(ComplexF64(b^2-4a*c))
    r1 = quadratic(a, sqr_term, b)
    r2 = quadratic(a, - sqr_term, b)
    # if return keyword is omitted the last term is returned
    r1, r2
end

print(quadratic2(2.0, -2.0, -12.0))

(3.0 + 0.0im, -2.0 - 0.0im)

## Strings

In [5]:
#char
c = 'a'
println(typeof(c),"\tTO_ASCII ->\t",Int(c))

c = "a"
println(typeof(c), "\ttoUPPER ->\t", uppercase(c))
c = "Qqs65aAF"
println(typeof(c), "\ttoLOWER ->\t", lowercase(c))

# show raw values 
show(lowercasefirst(c[end-1:end]));println()

#merge strings
println("$c to $c")
# use *  instead of +
println("$c"*"$c")

#evaluate
println("1+2 = $(1+2)")

s3 = string("this", " and", " that")
println(s3)

Char	TO_ASCII ->	97
String	toUPPER ->	A
String	toLOWER ->	qqs65aaf
"aF"
Qqs65aAF to Qqs65aAF
Qqs65aAFQqs65aAF
1+2 = 3
this and that


In [6]:
e_str1 = "2.710000008"
e_flt = parse(Float64, e_str1)
println(5*e_flt)

using Printf
# convert and format number to string
@printf "e_flt = %0.1f\n" e_flt
# or create a string
e_str2 = @sprintf("%0.3f", e_flt)

println("e_str1 == e_str2: $(e_str1 == e_str2)")

# available number format characters are f, e, g, c, s, p, d:
@printf "fix trailing precision: %0.3f\n" float(pi)
#> fix trailing precision: 3.142
@printf "scientific form: %0.6e\n" 1000pi
#> scientific form: 3.141593e+03
# g is not implemented yet
@printf "a character: %c\n" 'α'
#> a character: α
@printf "a string: %s\n" "look I'm a string!"
#> a string: look I'm a string!
@printf "right justify a string: %50s\n" "width 50, text right justified!"
#> right justify a string:                    width 50, text right justified!
@printf "a pointer: %p\n" 100000000
#> a pointer: 0x0000000005f5e100
@printf "print a integer: %d\n" 1e10
#> print an integer: 10000000000

13.55000004
e_flt = 2.7
e_str1 == e_str2: false
fix trailing precision: 3.142
scientific form: 3.141593e+03
a character: α
a string: look I'm a string!
right justify a string:                    width 50, text right justified!
a pointer: 0x0000000005f5e100
print a integer: 10000000000


In [7]:
s1 = "The quick brown fox jumps over the lazy dog α,β,γ"

println("a" < "b")
println("xylo" == "phone")
println(findfirst(isequal('x'), "xylo"))
println(occursin("xylo", "xylophone"))
println(repeat(".::.", 10))
println(join(["apples", "bananas", "pineapples"], ", ", " and "))
println(length("boom"))

true
false
1
true
.::..::..::..::..::..::..::..::..::..::.
apples, bananas and pineapples
4


In [8]:
println(firstindex("xyzzyx"))
println(lastindex("xyzzyx"))
println(length("xyzzyx", 1 , 5))

1
6
5


In [9]:
s1 = "The quick brown fox jumps over the lazy dog αβγ quickly"
println(replace(s1, "brown"=>"red"))
println(replace(s1, "quick"=>"fastly"))
println(replace(s1, "quick"=>"fastly", count=1))
println(replace(s1, r"quick(ly)?"=>s"fast", count=1))

The quick red fox jumps over the lazy dog αβγ quickly
The fastly brown fox jumps over the lazy dog αβγ fastlyly
The fastly brown fox jumps over the lazy dog αβγ quickly
The fast brown fox jumps over the lazy dog αβγ quickly


In [10]:
println(typeof(r"^\s*(?:#|$)"))
println(occursin(r"^\s*(?:#|$)", "# a comment"))
println(match(r"^\s*(?:#|$)", "# a comment"))
println(match(r"(a|b)(c)?(d)", "acd"))
println(match(r"(a|b)(c)?(d)", "ad"))
println(match(r"(a|b)(c)?(d)", "ad").match)
println(match(r"(a|b)(c)?(d)", "ad").captures)
println(match(r"(a|b)(c)?(d)", "ad").offsets)

Regex
true
RegexMatch("#")
RegexMatch("acd", 1="a", 2="c", 3="d")
RegexMatch("ad", 1="a", 2=nothing, 3="d")
ad
Union{Nothing, SubString{String}}["a", nothing, "d"]
[1, 0, 2]


In [11]:
r = eachmatch(r"[\w]{4,}", s1);
for i in r print("\"$(i.match)\" ") end

"quick" "brown" "jumps" "over" "lazy" "quickly" 

In [12]:
s1 = "M.O.C.H.A"
println(split(s1, "."))
#reverse split, starts from end
println(rsplit(s1, "."))
println(rsplit(s1, ".", limit=2))

SubString{String}["M", "O", "C", "H", "A"]
SubString{String}["M", "O", "C", "H", "A"]
SubString{String}["M.O.C.H", "A"]


In [13]:
using Dates

println(Date(1962, 7, 10))
d = Date(1962, 7, 10)
regex_d = Regex("Day " * string(day(d)))
match(regex_d, "It happened on Day 10")

1962-07-10


RegexMatch("Day 10")

## Arrays

In [14]:
function printsum(a)
    # summary generates a summary of an object
    println(summary(a), ": ", repr(a))
end

printsum (generic function with 1 method)

In [15]:
a1 = [1,2,3]
printsum(a1)

3-element Array{Int64,1}: [1, 2, 3]


In [16]:
# Empty Array, NO Type!
a2 = []
printsum(a2)

0-element Array{Any,1}: Any[]


In [17]:
# Empty Array, INT Type!
a3 = Int64[]
printsum(a3)

0-element Array{Int64,1}: Int64[]


In [18]:
xrange = 1:20
printsum(xrange)

20-element UnitRange{Int64}: 1:20


In [19]:
printsum(collect(xrange))

20-element Array{Int64,1}: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [20]:
printsum(Int128[2^i for i = 50:60])

11-element Array{Int128,1}: Int128[1125899906842624, 2251799813685248, 4503599627370496, 9007199254740992, 18014398509481984, 36028797018963968, 72057594037927936, 144115188075855872, 288230376151711744, 576460752303423488, 1152921504606846976]


In [21]:
push!(a1, 4)
printsum(a1)

4-element Array{Int64,1}: [1, 2, 3, 4]


In [22]:
a7 = repeat([0, 1],inner=[2],outer=[2])
printsum(a7)

8-element Array{Int64,1}: [0, 0, 1, 1, 0, 0, 1, 1]


In [23]:
a7 = repeat(collect(4:-1:1),inner=[2],outer=[2])
printsum(a7)

16-element Array{Int64,1}: [4, 4, 3, 3, 2, 2, 1, 1, 4, 4, 3, 3, 2, 2, 1, 1]


### Multidimensional Arrays

In [24]:
m1 = hcat(repeat([1,2],inner=[1],outer=[3*2]),
          repeat([1,2,3],inner=[2],outer=[2]),
          repeat([1,2,3,4],inner=[3],outer=[1]))
printsum(m1)

12×3 Array{Int64,2}: [1 1 1; 2 1 1; 1 2 1; 2 2 2; 1 3 2; 2 3 2; 1 1 3; 2 1 3; 1 2 3; 2 2 4; 1 3 4; 2 3 4]


In [25]:
m2 = repeat(m1,1,2)     # replicate m1 once into dim1 and twice into dim2
println("size: ", size(m2))

size: (12, 6)


In [26]:
m2 = repeat(m1,2,1)     # replicate m1 once into dim1 and twice into dim2
println("size: ", size(m2))

size: (24, 3)


In [27]:
m4 = [i+j+k for i=1:3, j=1:3, k=1:3]

3×3×3 Array{Int64,3}:
[:, :, 1] =
 3  4  5
 4  5  6
 5  6  7

[:, :, 2] =
 4  5  6
 5  6  7
 6  7  8

[:, :, 3] =
 5  6  7
 6  7  8
 7  8  9

In [28]:
m5 = ["Hi Im # $(i+2*(j-1 + 3*(k-1)))" for i=1:2, j=1:3, k=1:2]

2×3×2 Array{String,3}:
[:, :, 1] =
 "Hi Im # 1"  "Hi Im # 3"  "Hi Im # 5"
 "Hi Im # 2"  "Hi Im # 4"  "Hi Im # 6"

[:, :, 2] =
 "Hi Im # 7"  "Hi Im # 9"   "Hi Im # 11"
 "Hi Im # 8"  "Hi Im # 10"  "Hi Im # 12"

In [29]:
sum(m4[:,:,:]) 

162

In [30]:
[sum(m4[:,i,:]) for i =1:3]

3-element Array{Int64,1}:
 45
 54
 63

In [31]:
[maximum(m4[:,i,:]) for i =1:3]

3-element Array{Int64,1}:
 7
 8
 9

In [32]:
# squeeze
m5 = reshape(m4, (3,1,3,1,3,1))
dropdims(m5, dims=(2,4,6))

3×3×3 Array{Int64,3}:
[:, :, 1] =
 3  4  5
 4  5  6
 5  6  7

[:, :, 2] =
 4  5  6
 5  6  7
 6  7  8

[:, :, 3] =
 5  6  7
 6  7  8
 7  8  9

In [33]:
findmax([i+j for i=1:3, j=0:2], dims=(2))

([3; 4; 5], CartesianIndex{2}[CartesianIndex(1, 3); CartesianIndex(2, 3); CartesianIndex(3, 3)])

In [34]:
#reshape
m6 = [minimum([i,j,k]) for i=1:2, j=3:5, k=6:9]
permutedims(m6, (3,2,1))

4×3×2 Array{Int64,3}:
[:, :, 1] =
 1  1  1
 1  1  1
 1  1  1
 1  1  1

[:, :, 2] =
 2  2  2
 2  2  2
 2  2  2
 2  2  2

In [35]:
# elementwise and broadcasting
m8 = rand(2,2) .- sum(rand(2,2));
size(m8 .+ [1,1])

(2, 2)

In [36]:
mm = m8[:,1]
mm .*= 0.001

2-element Array{Float64,1}:
 -0.002135360327698008 
 -0.0027321525593972896

## Dictionaries

In [37]:
a1 = Dict(1=>"one", 2=>"two")
a1[3]="Three"
printsum(a1)

Dict{Int64,String} with 3 entries: Dict(2=>"two",3=>"Three",1=>"one")


In [38]:
a2 = Dict{Int64, AbstractString}()
a2[0] = "Zero"
for key in keys(a1)
    a2[key] = uppercasefirst(a1[key])
end
printsum(collect(values(a2)))

4-element Array{AbstractString,1}: AbstractString["Zero", "Two", "Three", "One"]


In [39]:
a3 = Dict([key=>@sprintf("%s", a2[key]) for key in keys(a2)])

Dict{Int64,String} with 4 entries:
  0 => "Zero"
  2 => "Two"
  3 => "Three"
  1 => "One"

In [40]:
a4 = Dict([key=>@sprintf("%s", haskey(a3,key)) for key in keys(a3)])

Dict{Int64,String} with 4 entries:
  0 => "true"
  2 => "true"
  3 => "true"
  1 => "true"

## Loops and Maps

In [41]:
for i in 1:5
    print(i, ", ")
end

1, 2, 3, 4, 5, 

In [42]:
for i = 1:5
    print(i, ", ")
end
println()

1, 2, 3, 4, 5, 


In [43]:
a1 = [1,2,3,4]
for i in a1
    print(i, ", ")
end
println()

1, 2, 3, 4, 


In [44]:
a2 = collect(1:20)
for i in a2
    if i % 2 != 0
        continue
    end
    print(i, ", ")
    if i >= 8
        break
    end
end
println()

2, 4, 6, 8, 


In [45]:
while !isempty(a1)
    print(pop!(a1), ", ")
end
println()

4, 3, 2, 1, 


In [46]:
d1 = Dict(1=>"one", 2=>"two", 3=>"three")
# dicts may be looped through using the keys function:
for k in sort(collect(keys(d1)))
    print(k, ": ", d1[k], ", ")
end
println()

1: one, 2: two, 3: three, 


In [47]:
a3 = ["one", "two", "three"]
for (i, v) in enumerate(a3)
    print(i, ": ", v, ", ")
end
println()

1: one, 2: two, 3: three, 


In [48]:
a4 = map((x) -> x^2, [1, 2, 3, 7])
print(a4)

[1, 4, 9, 49]

## Types

In [49]:
# simple typedef with no constructor
struct Person
    name::AbstractString
    male::Bool
    age::Int32
    children::Int32
end

Person("Julia", false, 4, 0)

Person("Julia", false, 4, 0)

In [50]:
Personslist = Person[]
push!(Personslist, Person("Guy", true, 34, 0))
push!(Personslist, Person("Doe", true, 14, 0))
printsum(Personslist)

2-element Array{Person,1}: Person[Person("Guy", true, 34, 0), Person("Doe", true, 14, 0)]


In [51]:
# typedef with constructor
struct Family
    name::AbstractString
    members::Array{AbstractString, 1}
    large_family::Bool
    Family(name::String) = new(name, AbstractString[name], false)
    Family(name::String, members::Array{String,1}) = new(name, members, length(members)>3)
end

In [52]:
familylist = Family[]

0-element Array{Family,1}

In [53]:
push!(familylist, Family("Joneses"))
push!(familylist, Family("joneses", ["anna", "bob", "charlie", "dick"]))
println(familylist)

Family[Family("Joneses", AbstractString["Joneses"], false), Family("joneses", AbstractString["anna", "bob", "charlie", "dick"], true)]


## I/O

In [54]:
tempfile = "Buzz.Fuzz"
f = open(tempfile, "w")
for record in familylist
    println(f, record)
end
close(f)

In [55]:
# "do" takes care of contexts
open(tempfile, "r") do f
    for line in eachline(f)
        println(line)
    end
end

Family("Joneses", AbstractString["Joneses"], false)
Family("joneses", AbstractString["anna", "bob", "charlie", "dick"], true)


## DataFrames

In [121]:
using DataFrames, CSV, RData, RDatasets

In [122]:
df = DataFrame(A = [1, 2], B = [exp(1), pi], C = ["xx", "xy"])
show(df)

2×3 DataFrame
│ Row │ A     │ B       │ C      │
│     │ Int64 │ Float64 │ String │
├─────┼───────┼─────────┼────────┤
│ 1   │ 1     │ 2.71828 │ xx     │
│ 2   │ 2     │ 3.14159 │ xy     │

In [123]:
show(df[1])

[1, 2]

In [124]:
show(df[:A])

[1, 2]

In [125]:
?CSV.write

```
CSV.write(file::Union{String, IO}, file; kwargs...) => file
table |> CSV.write(file::Union{String, IO}; kwargs...) => file
```

Write a [Tables.jl interface input](https://github.com/JuliaData/Tables.jl) to a csv file, given as an `IO` argument or String representing the file name to write to.

Keyword arguments include:

  * `delim::Union{Char, String}=','`: a character or string to print out as the file's delimiter
  * `quotechar::Char='"'`: character to use for quoting text fields that may contain delimiters or newlines
  * `openquotechar::Char`: instead of `quotechar`, use `openquotechar` and `closequotechar` to support different starting and ending quote characters
  * `escapechar::Char='\'`: character used to escape quote characters in a text field
  * `missingstring::String=""`: string to print
  * `dateformat=Dates.default_format(T)`: the date format string to use for printing out Date & DateTime columns
  * `append=false`: whether to append writing to an existing file/IO, if `true`, it will not write column names by default
  * `writeheader=!append`: whether to write an initial row of delimited column names, not written by default if appending
  * `header`: pass a list of column names (Symbols or Strings) to use instead of the column names of the input table


In [146]:
# load adn save
iris = dataset("datasets","iris")
CSV.write("iris.csv", iris)
iris = CSV.read("iris.csv")
first(iris, 6)

6×5 DataFrame
│ Row │ SepalLength │ SepalWidth │ PetalLength │ PetalWidth │ Species │
│     │ Float64⍰    │ Float64⍰   │ Float64⍰    │ Float64⍰   │ String⍰ │
├─────┼─────────────┼────────────┼─────────────┼────────────┼─────────┤
│ 1   │ 5.1         │ 3.5        │ 1.4         │ 0.2        │ setosa  │
│ 2   │ 4.9         │ 3.0        │ 1.4         │ 0.2        │ setosa  │
│ 3   │ 4.7         │ 3.2        │ 1.3         │ 0.2        │ setosa  │
│ 4   │ 4.6         │ 3.1        │ 1.5         │ 0.2        │ setosa  │
│ 5   │ 5.0         │ 3.6        │ 1.4         │ 0.2        │ setosa  │
│ 6   │ 5.4         │ 3.9        │ 1.7         │ 0.4        │ setosa  │

In [147]:
show(names(iris))

Symbol[:SepalLength, :SepalWidth, :PetalLength, :PetalWidth, :Species]

In [148]:
show(eltypes(iris))

Union[Union{Missing, Float64}, Union{Missing, Float64}, Union{Missing, Float64}, Union{Missing, Float64}, Union{Missing, String}]

In [149]:
show(iris[iris[:Species] .== "setosa", :])

50×5 DataFrame
│ Row │ SepalLength │ SepalWidth │ PetalLength │ PetalWidth │ Species │
│     │ Float64⍰    │ Float64⍰   │ Float64⍰    │ Float64⍰   │ String⍰ │
├─────┼─────────────┼────────────┼─────────────┼────────────┼─────────┤
│ 1   │ 5.1         │ 3.5        │ 1.4         │ 0.2        │ setosa  │
│ 2   │ 4.9         │ 3.0        │ 1.4         │ 0.2        │ setosa  │
│ 3   │ 4.7         │ 3.2        │ 1.3         │ 0.2        │ setosa  │
│ 4   │ 4.6         │ 3.1        │ 1.5         │ 0.2        │ setosa  │
│ 5   │ 5.0         │ 3.6        │ 1.4         │ 0.2        │ setosa  │
│ 6   │ 5.4         │ 3.9        │ 1.7         │ 0.4        │ setosa  │
│ 7   │ 4.6         │ 3.4        │ 1.4         │ 0.3        │ setosa  │
⋮
│ 43  │ 4.4         │ 3.2        │ 1.3         │ 0.2        │ setosa  │
│ 44  │ 5.0         │ 3.5        │ 1.6         │ 0.6        │ setosa  │
│ 45  │ 5.1         │ 3.8        │ 1.9         │ 0.4        │ setosa  │
│ 46  │ 4.8         │ 3.0        │ 1.4         

In [150]:
show(by(iris, :Species, df -> size(df, 1)))

3×2 DataFrame
│ Row │ Species    │ x1    │
│     │ String⍰    │ Int64 │
├─────┼────────────┼───────┤
│ 1   │ setosa     │ 50    │
│ 2   │ versicolor │ 50    │
│ 3   │ virginica  │ 50    │

In [151]:
sum(iris[:SepalLength]) + sum(iris[:SepalWidth])

1335.1000000000004

In [152]:
# pivot
tabulated = by(
    iris,
    [:Species, :SepalLength, :SepalWidth],
    df -> size(df, 1)
)
show(tabulated)

127×4 DataFrame
│ Row │ Species   │ SepalLength │ SepalWidth │ x1    │
│     │ String⍰   │ Float64⍰    │ Float64⍰   │ Int64 │
├─────┼───────────┼─────────────┼────────────┼───────┤
│ 1   │ setosa    │ 5.1         │ 3.5        │ 2     │
│ 2   │ setosa    │ 4.9         │ 3.0        │ 1     │
│ 3   │ setosa    │ 4.7         │ 3.2        │ 2     │
│ 4   │ setosa    │ 4.6         │ 3.1        │ 1     │
│ 5   │ setosa    │ 5.0         │ 3.6        │ 1     │
│ 6   │ setosa    │ 5.4         │ 3.9        │ 2     │
│ 7   │ setosa    │ 4.6         │ 3.4        │ 1     │
⋮
│ 120 │ virginica │ 6.0         │ 3.0        │ 1     │
│ 121 │ virginica │ 6.9         │ 3.1        │ 2     │
│ 122 │ virginica │ 6.7         │ 3.1        │ 1     │
│ 123 │ virginica │ 6.8         │ 3.2        │ 1     │
│ 124 │ virginica │ 6.7         │ 3.0        │ 1     │
│ 125 │ virginica │ 6.3         │ 2.5        │ 1     │
│ 126 │ virginica │ 6.2         │ 3.4        │ 1     │
│ 127 │ virginica │ 5.9         │ 3.0        │ 

In [153]:
gdf = groupby(iris,[:Species, :SepalLength, :SepalWidth])
for idf in gdf
    print(size(idf,1),",")
end

2,1,2,1,1,2,1,2,1,2,1,2,2,1,1,1,1,3,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,2,2,2,1,1,1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,2,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,

In [156]:
# insert random numbers at col 5:
irisr = insertcols!(copy(iris), 5, :randCol => rand(nrow(iris)))
first(irisr, 6)

6×6 DataFrame. Omitted printing of 1 columns
│ Row │ SepalLength │ SepalWidth │ PetalLength │ PetalWidth │ randCol  │
│     │ Float64⍰    │ Float64⍰   │ Float64⍰    │ Float64⍰   │ Float64  │
├─────┼─────────────┼────────────┼─────────────┼────────────┼──────────┤
│ 1   │ 5.1         │ 3.5        │ 1.4         │ 0.2        │ 0.40665  │
│ 2   │ 4.9         │ 3.0        │ 1.4         │ 0.2        │ 0.656743 │
│ 3   │ 4.7         │ 3.2        │ 1.3         │ 0.2        │ 0.620909 │
│ 4   │ 4.6         │ 3.1        │ 1.5         │ 0.2        │ 0.684613 │
│ 5   │ 5.0         │ 3.6        │ 1.4         │ 0.2        │ 0.192139 │
│ 6   │ 5.4         │ 3.9        │ 1.7         │ 0.4        │ 0.530261 │

In [157]:
deletecols!(irisr, :randCol)
first(irisr, 6)

6×5 DataFrame
│ Row │ SepalLength │ SepalWidth │ PetalLength │ PetalWidth │ Species │
│     │ Float64⍰    │ Float64⍰   │ Float64⍰    │ Float64⍰   │ String⍰ │
├─────┼─────────────┼────────────┼─────────────┼────────────┼─────────┤
│ 1   │ 5.1         │ 3.5        │ 1.4         │ 0.2        │ setosa  │
│ 2   │ 4.9         │ 3.0        │ 1.4         │ 0.2        │ setosa  │
│ 3   │ 4.7         │ 3.2        │ 1.3         │ 0.2        │ setosa  │
│ 4   │ 4.6         │ 3.1        │ 1.5         │ 0.2        │ setosa  │
│ 5   │ 5.0         │ 3.6        │ 1.4         │ 0.2        │ setosa  │
│ 6   │ 5.4         │ 3.9        │ 1.7         │ 0.4        │ setosa  │